---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
        - inc
        - ctp
    checks:
      Controversial/CamelCasePropertyName:
        enabled: false
  phan:
    enabled: true
    config:
      file_extensions: "php,inc,ctp"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,ctp"
    checks:
      Generic WhiteSpace DisallowTabIndent TabsUsed:
        enabled: false
      PSR1 Classes ClassDeclaration MissingNamespace:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.ctp"
exclude_paths:
  - webroot
