checks:
    php:
        sql_injection_vulnerabilities: true
        return_in_constructor: true
        require_php_tag_first: true
        no_short_open_tag: true
        no_exit: true
        no_eval: true
        return_doc_comments: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_todo_comments: true
        encourage_single_quotes: true
        simplify_boolean_return: true
        uppercase_constants: true
        no_new_line_at_end_of_file: true
        return_doc_comment_if_not_inferrable: true
        no_long_variable_names:
            maximum: '20'
filter:
    excluded_paths:
        - 'app/webroot'
coding_style:
    php: {  }
